/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-10-04 17:40:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nt.connection.GetConnectionPool;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class Customer_002dMaster_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("com.nt.connection.GetConnectionPool");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<!--[if lt IE 7]>      <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]>         <html class=\"no-js lt-ie9\" lang=\"\"> <![endif]-->\r\n");
      out.write("<!--[if gt IE 8]><!--> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html class=\"no-js\" lang=\"\"> <!--<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>car rental</title>\r\n");
      out.write("    <meta name=\"description\" content=\"Ela Admin - HTML5 Admin Template\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"http://icons.iconarchive.com/icons/graphicloads/colorful-long-shadow/256/Car-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"http://icons.iconarchive.com/icons/graphicloads/colorful-long-shadow/256/Car-icon.png\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/cs-skin-elastic.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("    <!-- <script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js\"></script> -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("   \r\n");
      out.write("   <style>\r\n");
      out.write("    #weatherWidget .currentDesc {\r\n");
      out.write("        color: #ffffff!important;\r\n");
      out.write("    }\r\n");
      out.write("        .traffic-chart {\r\n");
      out.write("            min-height: 335px;\r\n");
      out.write("        }\r\n");
      out.write("        #flotPie1  {\r\n");
      out.write("            height: 150px;\r\n");
      out.write("        }\r\n");
      out.write("        #flotPie1 td {\r\n");
      out.write("            padding:3px;\r\n");
      out.write("        }\r\n");
      out.write("        #flotPie1 table {\r\n");
      out.write("            top: 20px!important;\r\n");
      out.write("            right: -10px!important;\r\n");
      out.write("        }\r\n");
      out.write("        .chart-container {\r\n");
      out.write("            display: table;\r\n");
      out.write("            min-width: 270px ;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            padding-top: 10px;\r\n");
      out.write("            padding-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        #flotLine5  {\r\n");
      out.write("             height: 105px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #flotBarChart {\r\n");
      out.write("            height: 150px;\r\n");
      out.write("        }\r\n");
      out.write("        #cellPaiChart{\r\n");
      out.write("            height: 160px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #wrapper-content {\r\n");
      out.write("    background: #f1f2f7;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    min-height: 1200px;\r\n");
      out.write("    padding: 15px 15px 35px 15px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody > tr > td:first-child {\r\n");
      out.write("    font-size: 1.125em;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody > tr > td {\r\n");
      out.write("    font-size: 0.875em;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-top: 1px solid #e7ebee;\r\n");
      out.write("    padding: 12px 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Left Panel -->\r\n");
      out.write("    <aside id=\"left-panel\" class=\"left-panel\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-sm navbar-default\">\r\n");
      out.write("            <div id=\"main-menu\" class=\"main-menu collapse navbar-collapse\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li class=\"active\">\r\n");
      out.write("                        <a href=\"index.html\"><i class=\"menu-icon fa fa-laptop\"></i>Dashboard </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  <!--  <li class=\"menu-title\">UI elements</li>--><!-- /.menu-title -->\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-cogs\"></i>Settings</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">                          \r\n");
      out.write("                    <!----      <li><i class=\"fa fa-puzzle-piece\"></i><a href=\"Branch-Master.html\">Branch Master</a></li> --> \r\n");
      out.write("                            <li><i class=\"fa fa-id-badge\"></i><a href=\"Car-Category.html\">Car Category</a></li>\r\n");
      out.write("                            <li><i class=\"fa fa-bars\"></i><a href=\"Discount-Configuration.html\">Discount Configuration</a></li>\r\n");
      out.write("\r\n");
      out.write("                            <li><i class=\"fa fa-id-card-o\"></i><a href=\"User-Master.html\">User Master</a></li>\r\n");
      out.write("                            <li><i class=\"fa fa-exclamation-triangle\"></i><a href=\"User-Rights.html\">User Rights</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-cab\"></i>Car Master</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"fa fa-table\"></i><a href=\"Car-Setup.html\">Car Setup</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-group\"></i>Customers</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-th\"></i><a href=\"Customer-Master.html\">Customer Master</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-th\"></i><a href=\"Customer-History.html\">Customer History</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                  <!--  <li class=\"menu-title\">Icons</li>--><!-- /.menu-title -->\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-exchange\"></i>Driver</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-fort-awesome\"></i><a href=\"Driver-Master.html\">Driver Master</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon ti-themify-logo\"></i><a href=\"Driver-History.html\">Driver History</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-bank\"></i>Booking</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-fort-awesome\"></i><a href=\"Book-Car.html\">Book Car</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon ti-themify-logo\"></i><a href=\"View-Booking.html\">View Booking</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon ti-themify-logo\"></i><a href=\"Check-Car-Availability.html\">Check Car Availability</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-maxcdn\"></i>Service Management</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-line-chart\"></i><a href=\"Maintenance-Master.html\">Maintenance Master</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-area-chart\"></i><a href=\"Maintenance-Alerts.html\">Maintenance Alerts</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-maxcdn\"></i>Mechanic</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-map-o\"></i><a href=\"Mechanic-Master.html\">Mechanic Master</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  <!-- <li class=\"menu-title\">Extras</li>--><!-- /.menu-title -->\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-anchor\"></i>Insurance</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"Insurance-Master.html\">Insurance Master</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"Car-Insurance.html\">Car Insurance</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-envelope\"></i>Traffic Fine</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"Traffic-Fine-Management.html\">Traffic Fine Management</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"Fine-History.html\">Fine History</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-dollar\"></i>Expense</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"Expense-Types.html\">Expense Types</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"Daily-Expense.html\">Daily Expense</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"menu-item-has-children dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"> <i class=\"menu-icon fa fa-recycle\"></i>Reports</a>\r\n");
      out.write("                        <ul class=\"sub-menu children dropdown-menu\">\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"vehicleSummary.html\">Vehicle Summary</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-sign-in\"></i><a href=\"rental-history.html\">Rental History</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Repairs-Reports.html\">Repairs Reports</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Maintenance-Alert.html\">Maintenance Alert</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Daily-Business-Report.html\">Daily Business Report</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Daily-Cash-Summary.html\">Daily Cash Summary</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Reservations-Report.html\">Reservations Report</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Salesby-Employee-Report.html\">Sales by Employee Report</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Customer-Master-Report.html\">Customer Master Report</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Customer-Booking-Report.html\">Customer Booking Report</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Expense-Report.html\">Expense Report</a></li>\r\n");
      out.write("                            <li><i class=\"menu-icon fa fa-paper-plane\"></i><a href=\"Trail-Balance.html\">Trail Balance</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div><!-- /.navbar-collapse -->\r\n");
      out.write("        </nav>\r\n");
      out.write("    </aside>\r\n");
      out.write("    <!-- /#left-panel -->\r\n");
      out.write("    <!-- Right Panel -->\r\n");
      out.write("    <div id=\"right-panel\" class=\"right-panel\">\r\n");
      out.write("        <!-- Header-->\r\n");
      out.write("        <header id=\"header\" class=\"header\">\r\n");
      out.write("            <div class=\"top-left\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#\" style=\"color:darkorchid\">Car Rental</a>\r\n");
      out.write("                    <a class=\"navbar-brand hidden\" href=\"#\"><img src=\"images/logo2.png\" alt=\"Logo\"></a>\r\n");
      out.write("                    <a id=\"menuToggle\" class=\"menutoggle\"><i class=\"fa fa-bars\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top-right\">\r\n");
      out.write("                <div class=\"header-menu\">\r\n");
      out.write("                    <div class=\"header-left\">\r\n");
      out.write("                        <button class=\"search-trigger\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                        <div class=\"form-inline\">\r\n");
      out.write("                            <form class=\"search-form\">\r\n");
      out.write("                                <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search ...\" aria-label=\"Search\">\r\n");
      out.write("                                <button class=\"search-close\" type=\"submit\"><i class=\"fa fa-close\"></i></button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"dropdown for-notification\">\r\n");
      out.write("                            <button class=\"btn btn-secondary dropdown-toggle\" type=\"button\" id=\"notification\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fa fa-bell\"></i>\r\n");
      out.write("                                <span class=\"count bg-danger\">3</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <div class=\"dropdown-menu\" aria-labelledby=\"notification\">\r\n");
      out.write("                                <p class=\"red\">You have 3 Notification</p>\r\n");
      out.write("                                <a class=\"dropdown-item media\" href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-check\"></i>\r\n");
      out.write("                                    <p>Server #1 overloaded.</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item media\" href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-info\"></i>\r\n");
      out.write("                                    <p>Server #2 overloaded.</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item media\" href=\"#\">\r\n");
      out.write("                                    <i class=\"fa fa-warning\"></i>\r\n");
      out.write("                                    <p>Server #3 overloaded.</p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"dropdown for-message\">\r\n");
      out.write("                            <button class=\"btn btn-secondary dropdown-toggle\" type=\"button\" id=\"message\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("                                <span class=\"count bg-primary\">4</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <div class=\"dropdown-menu\" aria-labelledby=\"message\">\r\n");
      out.write("                                <p class=\"red\">You have 4 Mails</p>\r\n");
      out.write("                                <a class=\"dropdown-item media\" href=\"#\">\r\n");
      out.write("                                    <span class=\"photo media-left\"><img alt=\"avatar\" src=\"images/avatar/1.jpg\"></span>\r\n");
      out.write("                                    <div class=\"message media-body\">\r\n");
      out.write("                                        <span class=\"name float-left\">Jonathan Smith</span>\r\n");
      out.write("                                        <span class=\"time float-right\">Just now</span>\r\n");
      out.write("                                        <p>Hello, this is an example msg</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item media\" href=\"#\">\r\n");
      out.write("                                    <span class=\"photo media-left\"><img alt=\"avatar\" src=\"images/avatar/2.jpg\"></span>\r\n");
      out.write("                                    <div class=\"message media-body\">\r\n");
      out.write("                                        <span class=\"name float-left\">Jack Sanders</span>\r\n");
      out.write("                                        <span class=\"time float-right\">5 minutes ago</span>\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amet, consectetur</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item media\" href=\"#\">\r\n");
      out.write("                                    <span class=\"photo media-left\"><img alt=\"avatar\" src=\"images/avatar/3.jpg\"></span>\r\n");
      out.write("                                    <div class=\"message media-body\">\r\n");
      out.write("                                        <span class=\"name float-left\">Cheryl Wheeler</span>\r\n");
      out.write("                                        <span class=\"time float-right\">10 minutes ago</span>\r\n");
      out.write("                                        <p>Hello, this is an example msg</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item media\" href=\"#\">\r\n");
      out.write("                                    <span class=\"photo media-left\"><img alt=\"avatar\" src=\"images/avatar/4.jpg\"></span>\r\n");
      out.write("                                    <div class=\"message media-body\">\r\n");
      out.write("                                        <span class=\"name float-left\">Rachel Santos</span>\r\n");
      out.write("                                        <span class=\"time float-right\">15 minutes ago</span>\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amet, consectetur</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"user-area dropdown float-right\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle active\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            <img class=\"user-avatar rounded-circle\" src=\"images/admin.jpg\" alt=\"User Avatar\">\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"user-menu dropdown-menu\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"#\"><i class=\"fa fa- user\"></i>My Profile</a>\r\n");
      out.write("\r\n");
      out.write("                            <a class=\"nav-link\" href=\"#\"><i class=\"fa fa- user\"></i>Notifications <span class=\"count\">13</span></a>\r\n");
      out.write("\r\n");
      out.write("                            <a class=\"nav-link\" href=\"#\"><i class=\"fa fa -cog\"></i>Settings</a>\r\n");
      out.write("\r\n");
      out.write("                            <a class=\"nav-link\" href=\"login.html\"><i class=\"fa fa-power -off\"></i>Logout</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- /#header -->\r\n");
      out.write("        <!-- Content -->\r\n");
      out.write("           \r\n");
      out.write("             <div class=\"row\">\r\n");
      out.write("                 <div class=\"col-lg-12\">\r\n");
      out.write("                     <div id=\"content-header\" class=\"clearfix\">\r\n");
      out.write("                         <div class=\"pull-left\">\r\n");
      out.write("                             <ol class=\"breadcrumb\">\r\n");
      out.write("                                 <li class=\"breadcrumb-item\"><a href=\"#\">home</a></li>\r\n");
      out.write("                                 <li class=\"breadcrumb-item\"><a href=\"#\">Costomer Master</a></li>\r\n");
      out.write("                             </ol>\r\n");
      out.write("                         </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\r\n");
      out.write("             <!--table branchmaster-->\r\n");
      out.write("\r\n");
      out.write("             <div id=\"wrapper-content\">\r\n");
      out.write("                         \r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"main-box clearfix\">\r\n");
      out.write("                            <header class=\"main-box-header clearfix\">\r\n");
      out.write("                                <h2 class=\"pull-left\">Customer</h2>\r\n");
      out.write("                                <div class=\"filter-block pull-right\">\r\n");
      out.write("                                    \r\n");
      out.write("                                    <a href=\"Addcustomer.html\" class=\"btn btn-primary pull-right\">\r\n");
      out.write("                                        <i class=\"fa fa-plus-circle fa-lg\"></i> Add CustomerØ¡\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </header>\r\n");
      out.write("                            <div class=\"main-box-body clearfix\" style=\"overflow:auto;\">\r\n");
      out.write("                                <div id=\"ContentPlaceHolder1_divTable\">\r\n");
      out.write("                                            </div><div id=\"dataTables-example_wrapper\" class=\"dataTables_wrapper form-inline dt-bootstrap no-footer\"><div class=\"top\"><div id=\"dataTables-example_filter\" class=\"dataTables_filter\"><label>Search:<input type=\"search\" class=\"form-control input-sm\" placeholder=\"\" aria-controls=\"dataTables-example\"></label></div><div class=\"DTTT_container\"></div></div><table class=\"table table-striped table-bordered table-hover dataTable no-footer\" style=\"font-size: small\" id=\"dataTables-example\" role=\"grid\" aria-describedby=\"dataTables-example_info\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr role=\"row\">\r\n");
      out.write("                                        <th style=\"text-align: center; width: 118.4px;\" class=\"sorting_asc\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-sort=\"ascending\" aria-label=\"Customer Name Ø§Ø³Ù Ø§ÙØ²Ø¨ÙÙ: activate to sort column descending\">SNO</th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 64.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"LandLine 1 : activate to sort column ascending\">Customer Name </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 64.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"LandLine 2 : activate to sort column ascending\">LandLine 2 -</th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 64.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Mobile 1 - : activate to sort column ascending\">Mobile 1 -</th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 72.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Address : activate to sort column ascending\">Address </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 65.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Passport No : activate to sort column ascending\">Passport No </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 60.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Passport Expiry Date : activate to sort column ascending\">Passport Expiry Date </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 72.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Driving License No : activate to sort column ascending\">Driving License No </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 76.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Nationality: activate to sort column ascending\">Nationality </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 64.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Ref Name : activate to sort column ascending\">Ref Name</th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 64.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Ref Phone : activate to sort column ascending\">Ref Phone </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 46.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Job Details : activate to sort column ascending\">Job Details </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 51.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Refer By : activate to sort column ascending\">Refer By </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 61.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Premium Customer : activate to sort column ascending\">Premium Customer </th>\r\n");
      out.write("                                          <th style=\"text-align: center; width: 51.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Customer Username: activate to sort column ascending\">Customer Username</th>\r\n");
      out.write("                                         <th style=\"text-align: center; width: 61.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Permission Customer : activate to sort column ascending\">Permission</th>\r\n");
      out.write("                                       \r\n");
      out.write("                                        <th style=\"text-align: center; width: 31.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Edit : activate to sort column ascending\">Edit </th>\r\n");
      out.write("                                        <th style=\"text-align: center; width: 40.4px;\" class=\"sorting\" tabindex=\"0\" aria-controls=\"dataTables-example\" rowspan=\"1\" colspan=\"1\" aria-label=\"Delete: activate to sort column ascending\">Delete </th>\r\n");
      out.write("                                       </tr>\r\n");
      out.write("\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        \r\n");
      out.write("                       ");


						Connection con=GetConnectionPool.getPooledConnection();
						Statement st=con.createStatement();
						ResultSet rs=st.executeQuery("select * from customerreg");
						int i=1;
						while(rs.next()){

				
      out.write("                 \r\n");
      out.write("\r\n");
      out.write("                                    <tr role=\"row\" class=\"odd\">\r\n");
      out.write("                                        <td style=\"text-align: center \" class=\"sorting_1\">");
      out.print(i  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("CUSTNAME")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getLong("LANDLINENO")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getLong("MOBILENO")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("ADDRESS")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("PASSPORTNO")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getDate("PASSPORTEXPIRYDATE")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("DRIVINGLINO") );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("NATIONALITY")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("REFNAME")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getLong("REFPHONENO") );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("JOBDETAILS")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("REFERBY")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("PREMIUMCUSTOMER")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">");
      out.print(rs.getString("USERNAME")  );
      out.write("</td>\r\n");
      out.write("                                        <td style=\"text-align: center;\"> \r\n");
      out.write("                                        <form action=\"permission\" method=\"POST\" onsubmit=\"return confirm('Do you want to submit ?')\">\r\n");
      out.write("                                        <input name=\"cid\" type=\"hidden\" value=\"");
      out.print(rs.getInt("sno"));
      out.write("\">\r\n");
      out.write("                                        ");

                                        if(rs.getInt("permission")!=1){
      out.write("\r\n");
      out.write("                                        \t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"permission\" value=\"1\"> Yes\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"permission\" value=\"0\" checked> NO\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
} else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"permission\" value=\"1\" checked> Yes\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"permission\" value=\"0\" > NO\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td style=\"text-align: center;\">&nbsp;&nbsp;<input type=\"submit\"> </form>\r\n");
      out.write("                                        <td style=\"text-align: center;\"><a href=\"DeleteCustomer?id=");
      out.print(rs.getInt("sno"));
      out.write(" \" onclick=\"return confirm('Do you really want to delete ?')\"><img width=\"20\" height=\"20\" src=\"images/delete.png\"></a></td>\r\n");
      out.write("                                    </tr>");
i=i+1; }
      out.write("\r\n");
      out.write("                                   \r\n");
      out.write("     </table><div class=\"bottom\"><div class=\"dataTables_info\" id=\"dataTables-example_info\" role=\"status\" aria-live=\"polite\">Showing entries</div></div><div class=\"clear\"></div></div>\r\n");
      out.write("\t\t\t\t\t");
 if(request.getAttribute("delete")!=null){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t<h4 style=\"color:red\">");
      out.print( request.getAttribute("delete"));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t");
  } 
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("\r\n");
      out.write("             </div>\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("        <footer class=\"site-footer\">\r\n");
      out.write("            <div class=\"footer-inner bg-white\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                        Copyright &copy; 2018 Ela Admin\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 text-right\">\r\n");
      out.write("                        Designed by <a href=\"https://colorlib.com\">Colorlib</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- /.site-footer -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- /#right-panel -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--  Chart js -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--Chartist Chart-->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/init/weather-init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/init/fullcalendar-init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--Local Stuff-->\r\n");
      out.write("    <script>\r\n");
      out.write("        jQuery(document).ready(function($) {\r\n");
      out.write("            \"use strict\";\r\n");
      out.write("\r\n");
      out.write("            // Pie chart flotPie1\r\n");
      out.write("            var piedata = [\r\n");
      out.write("                { label: \"Desktop visits\", data: [[1,32]], color: '#5c6bc0'},\r\n");
      out.write("                { label: \"Tab visits\", data: [[1,33]], color: '#ef5350'},\r\n");
      out.write("                { label: \"Mobile visits\", data: [[1,35]], color: '#66bb6a'}\r\n");
      out.write("            ];\r\n");
      out.write("\r\n");
      out.write("            $.plot('#flotPie1', piedata, {\r\n");
      out.write("                series: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        show: true,\r\n");
      out.write("                        radius: 1,\r\n");
      out.write("                        innerRadius: 0.65,\r\n");
      out.write("                        label: {\r\n");
      out.write("                            show: true,\r\n");
      out.write("                            radius: 2/3,\r\n");
      out.write("                            threshold: 1\r\n");
      out.write("                        },\r\n");
      out.write("                        stroke: {\r\n");
      out.write("                            width: 0\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                grid: {\r\n");
      out.write("                    hoverable: true,\r\n");
      out.write("                    clickable: true\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            // Pie chart flotPie1  End\r\n");
      out.write("            // cellPaiChart\r\n");
      out.write("            var cellPaiChart = [\r\n");
      out.write("                { label: \"Direct Sell\", data: [[1,65]], color: '#5b83de'},\r\n");
      out.write("                { label: \"Channel Sell\", data: [[1,35]], color: '#00bfa5'}\r\n");
      out.write("            ];\r\n");
      out.write("            $.plot('#cellPaiChart', cellPaiChart, {\r\n");
      out.write("                series: {\r\n");
      out.write("                    pie: {\r\n");
      out.write("                        show: true,\r\n");
      out.write("                        stroke: {\r\n");
      out.write("                            width: 0\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                legend: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                },grid: {\r\n");
      out.write("                    hoverable: true,\r\n");
      out.write("                    clickable: true\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("            // cellPaiChart End\r\n");
      out.write("            // Line Chart  #flotLine5\r\n");
      out.write("            var newCust = [[0, 3], [1, 5], [2,4], [3, 7], [4, 9], [5, 3], [6, 6], [7, 4], [8, 10]];\r\n");
      out.write("\r\n");
      out.write("            var plot = $.plot($('#flotLine5'),[{\r\n");
      out.write("                data: newCust,\r\n");
      out.write("                label: 'New Data Flow',\r\n");
      out.write("                color: '#fff'\r\n");
      out.write("            }],\r\n");
      out.write("            {\r\n");
      out.write("                series: {\r\n");
      out.write("                    lines: {\r\n");
      out.write("                        show: true,\r\n");
      out.write("                        lineColor: '#fff',\r\n");
      out.write("                        lineWidth: 2\r\n");
      out.write("                    },\r\n");
      out.write("                    points: {\r\n");
      out.write("                        show: true,\r\n");
      out.write("                        fill: true,\r\n");
      out.write("                        fillColor: \"#ffffff\",\r\n");
      out.write("                        symbol: \"circle\",\r\n");
      out.write("                        radius: 3\r\n");
      out.write("                    },\r\n");
      out.write("                    shadowSize: 0\r\n");
      out.write("                },\r\n");
      out.write("                points: {\r\n");
      out.write("                    show: true,\r\n");
      out.write("                },\r\n");
      out.write("                legend: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                },\r\n");
      out.write("                grid: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            // Line Chart  #flotLine5 End\r\n");
      out.write("            // Traffic Chart using chartist\r\n");
      out.write("            if ($('#traffic-chart').length) {\r\n");
      out.write("                var chart = new Chartist.Line('#traffic-chart', {\r\n");
      out.write("                  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],\r\n");
      out.write("                  series: [\r\n");
      out.write("                  [0, 18000, 35000,  25000,  22000,  0],\r\n");
      out.write("                  [0, 33000, 15000,  20000,  15000,  300],\r\n");
      out.write("                  [0, 15000, 28000,  15000,  30000,  5000]\r\n");
      out.write("                  ]\r\n");
      out.write("              }, {\r\n");
      out.write("                  low: 0,\r\n");
      out.write("                  showArea: true,\r\n");
      out.write("                  showLine: false,\r\n");
      out.write("                  showPoint: false,\r\n");
      out.write("                  fullWidth: true,\r\n");
      out.write("                  axisX: {\r\n");
      out.write("                    showGrid: true\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("                chart.on('draw', function(data) {\r\n");
      out.write("                    if(data.type === 'line' || data.type === 'area') {\r\n");
      out.write("                        data.element.animate({\r\n");
      out.write("                            d: {\r\n");
      out.write("                                begin: 2000 * data.index,\r\n");
      out.write("                                dur: 2000,\r\n");
      out.write("                                from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),\r\n");
      out.write("                                to: data.path.clone().stringify(),\r\n");
      out.write("                                easing: Chartist.Svg.Easing.easeOutQuint\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("            // Traffic Chart using chartist End\r\n");
      out.write("            //Traffic chart chart-js\r\n");
      out.write("            if ($('#TrafficChart').length) {\r\n");
      out.write("                var ctx = document.getElementById( \"TrafficChart\" );\r\n");
      out.write("                ctx.height = 150;\r\n");
      out.write("                var myChart = new Chart( ctx, {\r\n");
      out.write("                    type: 'line',\r\n");
      out.write("                    data: {\r\n");
      out.write("                        labels: [ \"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\", \"Jul\" ],\r\n");
      out.write("                        datasets: [\r\n");
      out.write("                        {\r\n");
      out.write("                            label: \"Visit\",\r\n");
      out.write("                            borderColor: \"rgba(4, 73, 203,.09)\",\r\n");
      out.write("                            borderWidth: \"1\",\r\n");
      out.write("                            backgroundColor: \"rgba(4, 73, 203,.5)\",\r\n");
      out.write("                            data: [ 0, 2900, 5000, 3300, 6000, 3250, 0 ]\r\n");
      out.write("                        },\r\n");
      out.write("                        {\r\n");
      out.write("                            label: \"Bounce\",\r\n");
      out.write("                            borderColor: \"rgba(245, 23, 66, 0.9)\",\r\n");
      out.write("                            borderWidth: \"1\",\r\n");
      out.write("                            backgroundColor: \"rgba(245, 23, 66,.5)\",\r\n");
      out.write("                            pointHighlightStroke: \"rgba(245, 23, 66,.5)\",\r\n");
      out.write("                            data: [ 0, 4200, 4500, 1600, 4200, 1500, 4000 ]\r\n");
      out.write("                        },\r\n");
      out.write("                        {\r\n");
      out.write("                            label: \"Targeted\",\r\n");
      out.write("                            borderColor: \"rgba(40, 169, 46, 0.9)\",\r\n");
      out.write("                            borderWidth: \"1\",\r\n");
      out.write("                            backgroundColor: \"rgba(40, 169, 46, .5)\",\r\n");
      out.write("                            pointHighlightStroke: \"rgba(40, 169, 46,.5)\",\r\n");
      out.write("                            data: [1000, 5200, 3600, 2600, 4200, 5300, 0 ]\r\n");
      out.write("                        }\r\n");
      out.write("                        ]\r\n");
      out.write("                    },\r\n");
      out.write("                    options: {\r\n");
      out.write("                        responsive: true,\r\n");
      out.write("                        tooltips: {\r\n");
      out.write("                            mode: 'index',\r\n");
      out.write("                            intersect: false\r\n");
      out.write("                        },\r\n");
      out.write("                        hover: {\r\n");
      out.write("                            mode: 'nearest',\r\n");
      out.write("                            intersect: true\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                } );\r\n");
      out.write("            }\r\n");
      out.write("            //Traffic chart chart-js  End\r\n");
      out.write("            // Bar Chart #flotBarChart\r\n");
      out.write("            $.plot(\"#flotBarChart\", [{\r\n");
      out.write("                data: [[0, 18], [2, 8], [4, 5], [6, 13],[8,5], [10,7],[12,4], [14,6],[16,15], [18, 9],[20,17], [22,7],[24,4], [26,9],[28,11]],\r\n");
      out.write("                bars: {\r\n");
      out.write("                    show: true,\r\n");
      out.write("                    lineWidth: 0,\r\n");
      out.write("                    fillColor: '#ffffff8a'\r\n");
      out.write("                }\r\n");
      out.write("            }], {\r\n");
      out.write("                grid: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            // Bar Chart #flotBarChart End\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
